# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otrasinvestigaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('Resumen', models.TextField()),
                ('Palabras_Clave', models.TextField()),
                ('Documento', models.FileField(null=True, upload_to='otrasinvestigaciones/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('Url', models.URLField(null=True)),
            ],
            options={
                'permissions': (('ver_otrasinvestigaciones', 'ver otrasinvesitgaciones'),),
            },
        ),
    ]
