# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Investigador', '0003_remove_investigador_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='publicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=500)),
                ('Nivel_Autoria', models.IntegerField()),
                ('Palabras_Clave', models.CharField(max_length=500)),
                ('Resumen', models.FileField(upload_to='publicaciones/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('Fecha', models.DateField()),
                ('Editorial', models.CharField(max_length=500)),
                ('DB_Indexada', models.CharField(max_length=500)),
                ('Url', models.URLField()),
                ('investigador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.investigador')),
            ],
        ),
    ]
