# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Investigador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=500, unique=True)),
                ('Archivo', models.FileField(null=True, upload_to='revista/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ISSN', models.CharField(blank=True, max_length=250, null=True)),
                ('Base_Indexada', models.CharField(blank=True, max_length=500, null=True)),
                ('Cuartil_Pertenece', models.CharField(blank=True, max_length=500, null=True)),
                ('Factor_Impacto', models.CharField(blank=True, max_length=500, null=True)),
                ('Url', models.URLField(blank=True, null=True)),
                ('investigador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.investigador')),
            ],
            options={
                'permissions': (('ver_Revista', 'ver Revista'),),
            },
        ),
    ]
