# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_perfil_documento'),
        ('datosprofesionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_profecionales',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfiles.Perfil'),
        ),
    ]
