# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.CharField(blank=True, max_length=10)),
                ('Direccion', models.CharField(blank=True, max_length=500)),
                ('Coordenadas', models.CharField(blank=True, max_length=450)),
                ('Telefono', models.CharField(blank=True, max_length=10)),
                ('Genero', models.CharField(blank=True, max_length=100)),
                ('Ciudadania', models.CharField(blank=True, max_length=100)),
                ('roles', models.ManyToManyField(to='roles.Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('ver_perfil', 'ver perfil'),),
            },
        ),
    ]
