# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_auto_20180119_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='Documento',
            field=models.FileField(null=True, upload_to='foto/'),
        ),
    ]
