# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_perfil_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='Documento',
            field=models.FileField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
