# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Investigador', '0002_auto_20171208_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulos_cientificos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=250,null=True)),
                ('Numero', models.CharField(blank=True, max_length=250,null=True)),
                ('Estado', models.CharField(blank=True, max_length=250,null=True)),
                ('Anio', models.IntegerField(blank=True, max_length=10,null=True)),
                ('ISSN', models.CharField(blank=True, max_length=250,null=True)),
                ('Base_Datos', models.CharField(blank=True, max_length=250,null=True)),
                ('Url', models.URLField(blank=True,null=True)),
                ('Fecha_Publicacion', models.DateField(blank=True,null=True)),
                ('investigador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.investigador')),
            ],
        ),
    ]
