# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_Cientificos', '0002_auto_20171208_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos_cientificos',
            options={'permissions': (('ver_articulo', 'ver articulo'),)},
        ),
    ]
