# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universidad', '0001_initial'),
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universidad.universidad'),
        ),
    ]
