# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_campus_universidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'permissions': (('ver_campus', 'ver campus'),)},
        ),
    ]
