# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('ver_Proyectos', 'ver Proyectos'),)},
        ),
    ]
