# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-10 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='participacionevento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('Nivel_Autoria', models.CharField(max_length=255)),
                ('Palabras_Clave', models.TextField()),
                ('Resumen', models.FileField(upload_to='eventos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('Nombre_Evento', models.CharField(max_length=255)),
                ('Nivel', models.IntegerField()),
                ('Lugar_Evento', models.CharField(max_length=255)),
            ],
        ),
    ]
