# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participacioneventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacionevento',
            name='Nivel',
            field=models.CharField(max_length=255),
        ),
    ]
