# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Investigador', '0002_auto_20171208_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='formacion_academica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel_Estudios', models.CharField(max_length=250, null=True)),
                ('Fecha_Fin_Estudios', models.DateField(null=True)),
                ('Nombre_Centro_Estudios', models.CharField(max_length=250, null=True)),
                ('investigador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.investigador')),
            ],
        ),
    ]
