# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('Resumen', models.TextField(null=True)),
                ('PalabrasClave', models.CharField(blank=True, max_length=300, null=True)),
                ('Documento', models.FileField(upload_to='libro/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ISBN', models.CharField(blank=True, max_length=50, null=True)),
                ('UbicacionFisica', models.CharField(blank=True, max_length=50, null=True)),
                ('Anio', models.CharField(blank=True, max_length=5, null=True)),
                ('Editorial', models.CharField(blank=True, max_length=50, null=True)),
                ('Url', models.URLField(blank=True, null=True)),
            ],
            options={
                'permissions': (('ver_libro', 'ver libro'),),
            },
        ),
    ]
