# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 19:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('Editorial', models.CharField(blank=True, max_length=50, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=50, null=True)),
                ('Resumen', models.FileField(upload_to='libro/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('Ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('Url', models.URLField(blank=True, null=True)),
                ('Anio', models.CharField(blank=True, max_length=5, null=True)),
                ('PalabrasClave', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
